### ISSUE TITLE
Ensure entity_id's are correct in format, warn user.

### ISSUE THREAD

**Issue by thundergreen** [Petro31/ad_who_used_the_door#1]
Hey i try getting your app running but get this error:

```
2020-01-31 23:47:54.122672 WARNING AppDaemon: ------------------------------------------------------------


2020-01-31 23:47:59.417896 WARNING AppDaemon: ------------------------------------------------------------


2020-01-31 23:47:59.418653 WARNING AppDaemon: Unexpected error during process_event()


2020-01-31 23:47:59.419355 WARNING AppDaemon: ------------------------------------------------------------


2020-01-31 23:47:59.420350 WARNING AppDaemon: Traceback (most recent call last):


  File "/usr/lib/python3.8/site-packages/appdaemon/events.py", line 179, in process_event


    await self.AD.state.process_state_callbacks(namespace, data)


  File "/usr/lib/python3.8/site-packages/appdaemon/state.py", line 199, in process_state_callbacks


    cdevice, centity = callback["entity"].split(".")


ValueError: too many values to unpack (expected 2)




2020-01-31 23:47:59.420770 WARNING AppDaemon: ------------------------------------------------------------


```

what does this mean?

**Comment by thundergreen** [comment]
This is my config:

```
main_door:
  module: who_used_the_door
  class: WhoUsedTheDoor
  sensor: lock.main_door
  people_tracker: sensor.people_tracker
  message_name: Main Door
  notify:
    door_ajar:
      timestamp: '%-I:%M:%S %p'
      duration: 120
      notify:
      - notify.thorsten
    door_open:
      timestamp: '%-I:%M:%S %p'
      quiet_window: 120
      notify:
      - notify.thorsten
events:
  module: people_tracker
  class: PeopleTracker
  guest_entity_id: input_boolean.guests
  entities:
  - person.emilie
  - person.thorsten.frohlich
  - person.evan
```

**Comment by Petro31** [comment]
Hmm, I don't know.  add log_level: INFO and show me what's in the logs

**Comment by Petro31** [comment]
What version of appdaemon are you using?

**Comment by thundergreen** [comment]
I'm using Appdaemon4. Where can I add log_level : info?

**Comment by Petro31** [comment]
in the configuration of the app.  It looks like people_tracker is giving you the problem, so just add it like this:
```
events:
  module: people_tracker
  class: PeopleTracker
  guest_entity_id: input_boolean.guests
  entities:
  - person.emilie
  - person.thorsten.frohlich
  - person.evan
  log_level: INFO
```

Also, rename the app.  That was a mistake on my part in the README.  Change to

```
people_tracker:
  module: people_tracker
  class: PeopleTracker
  guest_entity_id: input_boolean.guests
  entities:
  - person.emilie
  - person.thorsten.frohlich
  - person.evan
  log_level: INFO
```

**Comment by thundergreen** [comment]
Now my cnfig looks like:
```
main_door:
  module: who_used_the_door
  class: WhoUsedTheDoor
  sensor: lock.main_door
  people_tracker: sensor.people_tracker
  message_name: Main Door
  notify:
    door_ajar:
      timestamp: '%-I:%M:%S %p'
      duration: 120
      notify:
      - notify.thorsten
    door_open:
      timestamp: '%-I:%M:%S %p'
      quiet_window: 120
      notify:
      - notify.thorsten
      
people_tracker:
  module: people_tracker
  class: PeopleTracker
  guest_entity_id: input_boolean.guests
  entities:
  - person.emilie
  - person.thorsten.frohlich
  - person.evan
  log_level: INFO
```

And this the error thrown:

```
    await self.AD.state.process_state_callbacks(namespace, data)


  File "/usr/lib/python3.8/site-packages/appdaemon/state.py", line 199, in process_state_callbacks


    cdevice, centity = callback["entity"].split(".")


ValueError: too many values to unpack (expected 2)




2020-02-03 21:18:25.571558 WARNING AppDaemon: ------------------------------------------------------------


2020-02-03 21:18:25.645018 INFO AppDaemon: Previous message repeated 1 times


2020-02-03 21:18:25.654419 WARNING AppDaemon: Unexpected error during process_event()


2020-02-03 21:18:25.655028 WARNING AppDaemon: ------------------------------------------------------------


2020-02-03 21:18:25.655754 WARNING AppDaemon: Traceback (most recent call last):


  File "/usr/lib/python3.8/site-packages/appdaemon/events.py", line 179, in process_event


    await self.AD.state.process_state_callbacks(namespace, data)


  File "/usr/lib/python3.8/site-packages/appdaemon/state.py", line 199, in process_state_callbacks


    cdevice, centity = callback["entity"].split(".")


ValueError: too many values to unpack (expected 2)




2020-02-03 21:18:25.656344 WARNING AppDaemon: ------------------------------------------------------------


2020-02-03 21:18:25.668084 INFO AppDaemon: Previous message repeated 1 times


2020-02-03 21:18:25.679898 WARNING AppDaemon: Unexpected error during process_event()


2020-02-03 21:18:25.680573 WARNING AppDaemon: ------------------------------------------------------------


2020-02-03 21:18:25.681360 WARNING AppDaemon: Traceback (most recent call last):


  File "/usr/lib/python3.8/site-packages/appdaemon/events.py", line 179, in process_event


    await self.AD.state.process_state_callbacks(namespace, data)


  File "/usr/lib/python3.8/site-packages/appdaemon/state.py", line 199, in process_state_callbacks


    cdevice, centity = callback["entity"].split(".")


ValueError: too many values to unpack (expected 2)



```

**Comment by Petro31** [comment]
>  `- person.thorsten.frohlich`

Your problem is this entity_id: `person.thorsten.frohlich`  Too many dots.  Typo maybe?  I don't protect against that in my apps, maybe I should.

**Comment by thundergreen** [comment]
omg! thanks man! That's my error!! it should be: person.thorsten_frohlich not  person.thorsten.frohlich.. now errors are gone :)

**Comment by Petro31** [comment]
Cool!  Glad it works
